### ISSUE TITLE
ValueError: time data does not match format '%Y-%m-%dT%H:%M:%S.%f'

### ISSUE THREAD

**Issue by kolen** [yourlabs/django-session-security#46]
I didn't figure out when it happens, but it happens sometimes:

```
Traceback (most recent call last):
  File "/srv/www/someproj/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/srv/www/someproj/env/local/lib/python2.7/site-packages/session_security/middleware.py", line 35, in process_request
    self.update_last_activity(request, now)
  File "/srv/www/someproj/env/local/lib/python2.7/site-packages/session_security/middleware.py", line 52, in update_last_activity
    last_activity = get_last_activity(request.session)
  File "/srv/www/someproj/env/local/lib/python2.7/site-packages/session_security/utils.py", line 17, in get_last_activity
    '%Y-%m-%dT%H:%M:%S.%f')
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))

ValueError: time data '2015-07-13T23:37:26' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

When it happens, I get multiple exceptions for subsequent pages. For some reason, value in ``session['_session_security']`` appears without microseconds.

**Comment by jpic** [comment]
What kind of browser is this with ?

**Comment by kolen** [comment]
User agents were:
``Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36``
``Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36``

So probably Chrome 38 and 43.

**Comment by jpic** [comment]
A fix in python would be easier to test for now would you be able to do
that?
Le 14 juil. 2015 11:38, "Konstantin Mochalov" <notifications@github.com> a
écrit :

**Comment by kolen** [comment]
Sorry, I can't reproduce this, it happens randomly and currently doesn't happen.

**Comment by jpic** [comment]
Yes but we can expect that microseconds are missing in get_last_activity
can't we ?

On Tue, Jul 14, 2015 at 12:48 PM, Konstantin Mochalov <
notifications@github.com> wrote:

> Sorry, I can't reproduce this, it happens randomly and currently doesn't
> happen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yourlabs/django-session-security/issues/46#issuecomment-121198503>
> .
>



-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by PurpleToti** [comment]
This was fixed in #166 (merged 2026-04-24), which adds a fallback in `get_last_activity` to handle timestamps without microseconds. The fix is now part of the 2.6.8 release.
